version: '3.8'
services:
  app:
    build: .
    container_name: ap_discord_bot
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # This ensures the container loads environment variables from .env
    restart: unless-stopped
